/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessStats {
  'quotesSentCount' : bigint,
  'activeClientsCount' : bigint,
  'quotesAcceptedCount' : bigint,
  'totalJobsThisMonth' : bigint,
}
export interface Client {
  'id' : string,
  'fullName' : string,
  'isActive' : boolean,
  'gpsLocation' : [] | [string],
  'address' : string,
  'notes' : string,
  'phone' : string,
  'registrationDate' : Time,
}
export interface Garden {
  'id' : string,
  'specialObservations' : string,
  'clientId' : string,
  'avgWorkTime' : bigint,
  'grassType' : string,
  'sizeM2' : number,
  'maintenanceFrequency' : string,
  'requiredTools' : string,
  'terrainType' : string,
}
export interface Invoice {
  'id' : string,
  'clientId' : string,
  'invoiceDate' : Time,
  'totalAmount' : number,
  'servicesPerformed' : string,
  'nextMaintenanceDate' : Time,
}
export interface JobEntry {
  'id' : string,
  'startTime' : string,
  'status' : JobStatus,
  'clientId' : string,
  'endTime' : string,
  'scheduledDate' : string,
  'assignedWorker' : string,
  'serviceDescription' : string,
}
export type JobStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface MaintenanceSchedule {
  'id' : string,
  'clientId' : string,
  'gardenId' : string,
  'isActive' : boolean,
  'frequency' : string,
  'nextDate' : string,
}
export interface Prospect {
  'id' : string,
  'status' : ProspectStatus,
  'name' : string,
  'serviceRequested' : string,
  'address' : string,
  'phone' : string,
  'quoteDate' : Time,
}
export type ProspectStatus = { 'quoteSent' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Quote {
  'id' : string,
  'status' : QuoteStatus,
  'clientId' : string,
  'serviceDescription' : string,
  'creationDate' : Time,
  'expirationDate' : Time,
  'price' : number,
}
export type QuoteStatus = { 'pending' : null } |
  { 'sent' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'transactionDate' : Time,
  'transactionType' : TransactionType,
  'description' : string,
  'amount' : number,
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClient' : ActorMethod<[Client], undefined>,
  'addGarden' : ActorMethod<[Garden], undefined>,
  'addInvoice' : ActorMethod<[Invoice], undefined>,
  'addJob' : ActorMethod<[JobEntry], undefined>,
  'addMaintenanceSchedule' : ActorMethod<[MaintenanceSchedule], undefined>,
  'addProspect' : ActorMethod<[Prospect], undefined>,
  'addQuote' : ActorMethod<[Quote], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'convertProspectToClient' : ActorMethod<[string, string], undefined>,
  'deleteClient' : ActorMethod<[string], undefined>,
  'deleteGarden' : ActorMethod<[string], undefined>,
  'deleteInvoice' : ActorMethod<[string], undefined>,
  'deleteJob' : ActorMethod<[string], undefined>,
  'deleteMaintenanceSchedule' : ActorMethod<[string], undefined>,
  'deleteProspect' : ActorMethod<[string], undefined>,
  'deleteQuote' : ActorMethod<[string], undefined>,
  'deleteTransaction' : ActorMethod<[string], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllGardens' : ActorMethod<[], Array<Garden>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllJobs' : ActorMethod<[], Array<JobEntry>>,
  'getAllMaintenanceSchedules' : ActorMethod<[], Array<MaintenanceSchedule>>,
  'getAllProspects' : ActorMethod<[], Array<Prospect>>,
  'getAllQuotes' : ActorMethod<[], Array<Quote>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getBusinessStats' : ActorMethod<[], BusinessStats>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[string], Client>,
  'getGarden' : ActorMethod<[string], Garden>,
  'getInvoice' : ActorMethod<[string], Invoice>,
  'getJob' : ActorMethod<[string], JobEntry>,
  'getJobsByClient' : ActorMethod<[string], Array<JobEntry>>,
  'getJobsByDate' : ActorMethod<[string], Array<JobEntry>>,
  'getMaintenanceSchedule' : ActorMethod<[string], MaintenanceSchedule>,
  'getProspect' : ActorMethod<[string], Prospect>,
  'getQuote' : ActorMethod<[string], Quote>,
  'getTransaction' : ActorMethod<[string], Transaction>,
  'getTransactionsByMonthYear' : ActorMethod<
    [bigint, bigint],
    Array<Transaction>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClient' : ActorMethod<[Client], undefined>,
  'updateGarden' : ActorMethod<[Garden], undefined>,
  'updateInvoice' : ActorMethod<[Invoice], undefined>,
  'updateJob' : ActorMethod<[JobEntry], undefined>,
  'updateMaintenanceSchedule' : ActorMethod<[MaintenanceSchedule], undefined>,
  'updateProspect' : ActorMethod<[Prospect], undefined>,
  'updateQuote' : ActorMethod<[Quote], undefined>,
  'updateTransaction' : ActorMethod<[Transaction], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];