/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Client = IDL.Record({
  'id' : IDL.Text,
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
  'gpsLocation' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'registrationDate' : Time,
});
export const Garden = IDL.Record({
  'id' : IDL.Text,
  'specialObservations' : IDL.Text,
  'clientId' : IDL.Text,
  'avgWorkTime' : IDL.Int,
  'grassType' : IDL.Text,
  'sizeM2' : IDL.Float64,
  'maintenanceFrequency' : IDL.Text,
  'requiredTools' : IDL.Text,
  'terrainType' : IDL.Text,
});
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'clientId' : IDL.Text,
  'invoiceDate' : Time,
  'totalAmount' : IDL.Float64,
  'servicesPerformed' : IDL.Text,
  'nextMaintenanceDate' : Time,
});
export const JobStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const JobEntry = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Text,
  'status' : JobStatus,
  'clientId' : IDL.Text,
  'endTime' : IDL.Text,
  'scheduledDate' : IDL.Text,
  'assignedWorker' : IDL.Text,
  'serviceDescription' : IDL.Text,
});
export const MaintenanceSchedule = IDL.Record({
  'id' : IDL.Text,
  'clientId' : IDL.Text,
  'gardenId' : IDL.Text,
  'isActive' : IDL.Bool,
  'frequency' : IDL.Text,
  'nextDate' : IDL.Text,
});
export const ProspectStatus = IDL.Variant({
  'quoteSent' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Prospect = IDL.Record({
  'id' : IDL.Text,
  'status' : ProspectStatus,
  'name' : IDL.Text,
  'serviceRequested' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'quoteDate' : Time,
});
export const QuoteStatus = IDL.Variant({
  'pending' : IDL.Null,
  'sent' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Quote = IDL.Record({
  'id' : IDL.Text,
  'status' : QuoteStatus,
  'clientId' : IDL.Text,
  'serviceDescription' : IDL.Text,
  'creationDate' : Time,
  'expirationDate' : Time,
  'price' : IDL.Float64,
});
export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transactionDate' : Time,
  'transactionType' : TransactionType,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BusinessStats = IDL.Record({
  'quotesSentCount' : IDL.Nat,
  'activeClientsCount' : IDL.Nat,
  'quotesAcceptedCount' : IDL.Nat,
  'totalJobsThisMonth' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClient' : IDL.Func([Client], [], []),
  'addGarden' : IDL.Func([Garden], [], []),
  'addInvoice' : IDL.Func([Invoice], [], []),
  'addJob' : IDL.Func([JobEntry], [], []),
  'addMaintenanceSchedule' : IDL.Func([MaintenanceSchedule], [], []),
  'addProspect' : IDL.Func([Prospect], [], []),
  'addQuote' : IDL.Func([Quote], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'convertProspectToClient' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteClient' : IDL.Func([IDL.Text], [], []),
  'deleteGarden' : IDL.Func([IDL.Text], [], []),
  'deleteInvoice' : IDL.Func([IDL.Text], [], []),
  'deleteJob' : IDL.Func([IDL.Text], [], []),
  'deleteMaintenanceSchedule' : IDL.Func([IDL.Text], [], []),
  'deleteProspect' : IDL.Func([IDL.Text], [], []),
  'deleteQuote' : IDL.Func([IDL.Text], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllGardens' : IDL.Func([], [IDL.Vec(Garden)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobEntry)], ['query']),
  'getAllMaintenanceSchedules' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceSchedule)],
      ['query'],
    ),
  'getAllProspects' : IDL.Func([], [IDL.Vec(Prospect)], ['query']),
  'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getBusinessStats' : IDL.Func([], [BusinessStats], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Text], [Client], ['query']),
  'getGarden' : IDL.Func([IDL.Text], [Garden], ['query']),
  'getInvoice' : IDL.Func([IDL.Text], [Invoice], ['query']),
  'getJob' : IDL.Func([IDL.Text], [JobEntry], ['query']),
  'getJobsByClient' : IDL.Func([IDL.Text], [IDL.Vec(JobEntry)], ['query']),
  'getJobsByDate' : IDL.Func([IDL.Text], [IDL.Vec(JobEntry)], ['query']),
  'getMaintenanceSchedule' : IDL.Func(
      [IDL.Text],
      [MaintenanceSchedule],
      ['query'],
    ),
  'getProspect' : IDL.Func([IDL.Text], [Prospect], ['query']),
  'getQuote' : IDL.Func([IDL.Text], [Quote], ['query']),
  'getTransaction' : IDL.Func([IDL.Text], [Transaction], ['query']),
  'getTransactionsByMonthYear' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClient' : IDL.Func([Client], [], []),
  'updateGarden' : IDL.Func([Garden], [], []),
  'updateInvoice' : IDL.Func([Invoice], [], []),
  'updateJob' : IDL.Func([JobEntry], [], []),
  'updateMaintenanceSchedule' : IDL.Func([MaintenanceSchedule], [], []),
  'updateProspect' : IDL.Func([Prospect], [], []),
  'updateQuote' : IDL.Func([Quote], [], []),
  'updateTransaction' : IDL.Func([Transaction], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Client = IDL.Record({
    'id' : IDL.Text,
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
    'gpsLocation' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'registrationDate' : Time,
  });
  const Garden = IDL.Record({
    'id' : IDL.Text,
    'specialObservations' : IDL.Text,
    'clientId' : IDL.Text,
    'avgWorkTime' : IDL.Int,
    'grassType' : IDL.Text,
    'sizeM2' : IDL.Float64,
    'maintenanceFrequency' : IDL.Text,
    'requiredTools' : IDL.Text,
    'terrainType' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'clientId' : IDL.Text,
    'invoiceDate' : Time,
    'totalAmount' : IDL.Float64,
    'servicesPerformed' : IDL.Text,
    'nextMaintenanceDate' : Time,
  });
  const JobStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const JobEntry = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Text,
    'status' : JobStatus,
    'clientId' : IDL.Text,
    'endTime' : IDL.Text,
    'scheduledDate' : IDL.Text,
    'assignedWorker' : IDL.Text,
    'serviceDescription' : IDL.Text,
  });
  const MaintenanceSchedule = IDL.Record({
    'id' : IDL.Text,
    'clientId' : IDL.Text,
    'gardenId' : IDL.Text,
    'isActive' : IDL.Bool,
    'frequency' : IDL.Text,
    'nextDate' : IDL.Text,
  });
  const ProspectStatus = IDL.Variant({
    'quoteSent' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Prospect = IDL.Record({
    'id' : IDL.Text,
    'status' : ProspectStatus,
    'name' : IDL.Text,
    'serviceRequested' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'quoteDate' : Time,
  });
  const QuoteStatus = IDL.Variant({
    'pending' : IDL.Null,
    'sent' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Quote = IDL.Record({
    'id' : IDL.Text,
    'status' : QuoteStatus,
    'clientId' : IDL.Text,
    'serviceDescription' : IDL.Text,
    'creationDate' : Time,
    'expirationDate' : Time,
    'price' : IDL.Float64,
  });
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transactionDate' : Time,
    'transactionType' : TransactionType,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BusinessStats = IDL.Record({
    'quotesSentCount' : IDL.Nat,
    'activeClientsCount' : IDL.Nat,
    'quotesAcceptedCount' : IDL.Nat,
    'totalJobsThisMonth' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClient' : IDL.Func([Client], [], []),
    'addGarden' : IDL.Func([Garden], [], []),
    'addInvoice' : IDL.Func([Invoice], [], []),
    'addJob' : IDL.Func([JobEntry], [], []),
    'addMaintenanceSchedule' : IDL.Func([MaintenanceSchedule], [], []),
    'addProspect' : IDL.Func([Prospect], [], []),
    'addQuote' : IDL.Func([Quote], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'convertProspectToClient' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteClient' : IDL.Func([IDL.Text], [], []),
    'deleteGarden' : IDL.Func([IDL.Text], [], []),
    'deleteInvoice' : IDL.Func([IDL.Text], [], []),
    'deleteJob' : IDL.Func([IDL.Text], [], []),
    'deleteMaintenanceSchedule' : IDL.Func([IDL.Text], [], []),
    'deleteProspect' : IDL.Func([IDL.Text], [], []),
    'deleteQuote' : IDL.Func([IDL.Text], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllGardens' : IDL.Func([], [IDL.Vec(Garden)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobEntry)], ['query']),
    'getAllMaintenanceSchedules' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceSchedule)],
        ['query'],
      ),
    'getAllProspects' : IDL.Func([], [IDL.Vec(Prospect)], ['query']),
    'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getBusinessStats' : IDL.Func([], [BusinessStats], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Text], [Client], ['query']),
    'getGarden' : IDL.Func([IDL.Text], [Garden], ['query']),
    'getInvoice' : IDL.Func([IDL.Text], [Invoice], ['query']),
    'getJob' : IDL.Func([IDL.Text], [JobEntry], ['query']),
    'getJobsByClient' : IDL.Func([IDL.Text], [IDL.Vec(JobEntry)], ['query']),
    'getJobsByDate' : IDL.Func([IDL.Text], [IDL.Vec(JobEntry)], ['query']),
    'getMaintenanceSchedule' : IDL.Func(
        [IDL.Text],
        [MaintenanceSchedule],
        ['query'],
      ),
    'getProspect' : IDL.Func([IDL.Text], [Prospect], ['query']),
    'getQuote' : IDL.Func([IDL.Text], [Quote], ['query']),
    'getTransaction' : IDL.Func([IDL.Text], [Transaction], ['query']),
    'getTransactionsByMonthYear' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClient' : IDL.Func([Client], [], []),
    'updateGarden' : IDL.Func([Garden], [], []),
    'updateInvoice' : IDL.Func([Invoice], [], []),
    'updateJob' : IDL.Func([JobEntry], [], []),
    'updateMaintenanceSchedule' : IDL.Func([MaintenanceSchedule], [], []),
    'updateProspect' : IDL.Func([Prospect], [], []),
    'updateQuote' : IDL.Func([Quote], [], []),
    'updateTransaction' : IDL.Func([Transaction], [], []),
  });
};

export const init = ({ IDL }) => { return []; };