/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Prospect {
    id: string;
    status: ProspectStatus;
    name: string;
    serviceRequested: string;
    address: string;
    phone: string;
    quoteDate: Time;
}
export type Time = bigint;
export interface Garden {
    id: string;
    specialObservations: string;
    clientId: string;
    avgWorkTime: bigint;
    grassType: string;
    sizeM2: number;
    maintenanceFrequency: string;
    requiredTools: string;
    terrainType: string;
}
export interface Invoice {
    id: string;
    clientId: string;
    invoiceDate: Time;
    totalAmount: number;
    servicesPerformed: string;
    nextMaintenanceDate: Time;
}
export interface MaintenanceSchedule {
    id: string;
    clientId: string;
    gardenId: string;
    isActive: boolean;
    frequency: string;
    nextDate: string;
}
export interface BusinessStats {
    quotesSentCount: bigint;
    activeClientsCount: bigint;
    quotesAcceptedCount: bigint;
    totalJobsThisMonth: bigint;
}
export interface Transaction {
    id: string;
    transactionDate: Time;
    transactionType: TransactionType;
    description: string;
    amount: number;
}
export interface JobEntry {
    id: string;
    startTime: string;
    status: JobStatus;
    clientId: string;
    endTime: string;
    scheduledDate: string;
    assignedWorker: string;
    serviceDescription: string;
}
export interface Quote {
    id: string;
    status: QuoteStatus;
    clientId: string;
    serviceDescription: string;
    creationDate: Time;
    expirationDate: Time;
    price: number;
}
export interface Client {
    id: string;
    fullName: string;
    isActive: boolean;
    gpsLocation?: string;
    address: string;
    notes: string;
    phone: string;
    registrationDate: Time;
}
export interface UserProfile {
    name: string;
}
export enum JobStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum ProspectStatus {
    quoteSent = "quoteSent",
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum QuoteStatus {
    pending = "pending",
    sent = "sent",
    rejected = "rejected",
    accepted = "accepted"
}
export enum TransactionType {
    expense = "expense",
    income = "income"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addClient(client: Client): Promise<void>;
    addGarden(garden: Garden): Promise<void>;
    addInvoice(invoice: Invoice): Promise<void>;
    addJob(job: JobEntry): Promise<void>;
    addMaintenanceSchedule(schedule: MaintenanceSchedule): Promise<void>;
    addProspect(prospect: Prospect): Promise<void>;
    addQuote(quote: Quote): Promise<void>;
    addTransaction(transaction: Transaction): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    convertProspectToClient(prospectId: string, clientId: string): Promise<void>;
    deleteClient(id: string): Promise<void>;
    deleteGarden(id: string): Promise<void>;
    deleteInvoice(id: string): Promise<void>;
    deleteJob(id: string): Promise<void>;
    deleteMaintenanceSchedule(id: string): Promise<void>;
    deleteProspect(id: string): Promise<void>;
    deleteQuote(id: string): Promise<void>;
    deleteTransaction(id: string): Promise<void>;
    getAllClients(): Promise<Array<Client>>;
    getAllGardens(): Promise<Array<Garden>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllJobs(): Promise<Array<JobEntry>>;
    getAllMaintenanceSchedules(): Promise<Array<MaintenanceSchedule>>;
    getAllProspects(): Promise<Array<Prospect>>;
    getAllQuotes(): Promise<Array<Quote>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getBusinessStats(): Promise<BusinessStats>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(id: string): Promise<Client>;
    getGarden(id: string): Promise<Garden>;
    getInvoice(id: string): Promise<Invoice>;
    getJob(id: string): Promise<JobEntry>;
    getJobsByClient(clientId: string): Promise<Array<JobEntry>>;
    getJobsByDate(date: string): Promise<Array<JobEntry>>;
    getMaintenanceSchedule(id: string): Promise<MaintenanceSchedule>;
    getProspect(id: string): Promise<Prospect>;
    getQuote(id: string): Promise<Quote>;
    getTransaction(id: string): Promise<Transaction>;
    getTransactionsByMonthYear(_month: bigint, _year: bigint): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateClient(client: Client): Promise<void>;
    updateGarden(garden: Garden): Promise<void>;
    updateInvoice(invoice: Invoice): Promise<void>;
    updateJob(job: JobEntry): Promise<void>;
    updateMaintenanceSchedule(schedule: MaintenanceSchedule): Promise<void>;
    updateProspect(prospect: Prospect): Promise<void>;
    updateQuote(quote: Quote): Promise<void>;
    updateTransaction(transaction: Transaction): Promise<void>;
}
import type { Client as _Client, JobEntry as _JobEntry, JobStatus as _JobStatus, Prospect as _Prospect, ProspectStatus as _ProspectStatus, Quote as _Quote, QuoteStatus as _QuoteStatus, Time as _Time, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addClient(arg0: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClient(to_candid_Client_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClient(to_candid_Client_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addGarden(arg0: Garden): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGarden(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGarden(arg0);
            return result;
        }
    }
    async addInvoice(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvoice(arg0);
            return result;
        }
    }
    async addJob(arg0: JobEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(to_candid_JobEntry_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(to_candid_JobEntry_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMaintenanceSchedule(arg0: MaintenanceSchedule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaintenanceSchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaintenanceSchedule(arg0);
            return result;
        }
    }
    async addProspect(arg0: Prospect): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProspect(to_candid_Prospect_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProspect(to_candid_Prospect_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addQuote(arg0: Quote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuote(to_candid_Quote_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuote(to_candid_Quote_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTransaction(arg0: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_Transaction_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_Transaction_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async convertProspectToClient(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.convertProspectToClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertProspectToClient(arg0, arg1);
            return result;
        }
    }
    async deleteClient(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteGarden(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGarden(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGarden(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteJob(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteMaintenanceSchedule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaintenanceSchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaintenanceSchedule(arg0);
            return result;
        }
    }
    async deleteProspect(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProspect(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProspect(arg0);
            return result;
        }
    }
    async deleteQuote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuote(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGardens(): Promise<Array<Garden>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGardens();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGardens();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllJobs(): Promise<Array<JobEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMaintenanceSchedules(): Promise<Array<MaintenanceSchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMaintenanceSchedules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMaintenanceSchedules();
            return result;
        }
    }
    async getAllProspects(): Promise<Array<Prospect>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProspects();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProspects();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuotes(): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuotes();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuotes();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusinessStats(): Promise<BusinessStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessStats();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: string): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_Client_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_Client_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGarden(arg0: string): Promise<Garden> {
        if (this.processError) {
            try {
                const result = await this.actor.getGarden(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGarden(arg0);
            return result;
        }
    }
    async getInvoice(arg0: string): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return result;
        }
    }
    async getJob(arg0: string): Promise<JobEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_JobEntry_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_JobEntry_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByClient(arg0: string): Promise<Array<JobEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByClient(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByClient(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByDate(arg0: string): Promise<Array<JobEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByDate(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByDate(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaintenanceSchedule(arg0: string): Promise<MaintenanceSchedule> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceSchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceSchedule(arg0);
            return result;
        }
    }
    async getProspect(arg0: string): Promise<Prospect> {
        if (this.processError) {
            try {
                const result = await this.actor.getProspect(arg0);
                return from_candid_Prospect_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProspect(arg0);
            return from_candid_Prospect_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuote(arg0: string): Promise<Quote> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuote(arg0);
                return from_candid_Quote_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuote(arg0);
            return from_candid_Quote_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaction(arg0: string): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_Transaction_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_Transaction_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByMonthYear(arg0: bigint, arg1: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByMonthYear(arg0, arg1);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByMonthYear(arg0, arg1);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateClient(arg0: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(to_candid_Client_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(to_candid_Client_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateGarden(arg0: Garden): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGarden(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGarden(arg0);
            return result;
        }
    }
    async updateInvoice(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0);
            return result;
        }
    }
    async updateJob(arg0: JobEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(to_candid_JobEntry_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(to_candid_JobEntry_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMaintenanceSchedule(arg0: MaintenanceSchedule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaintenanceSchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaintenanceSchedule(arg0);
            return result;
        }
    }
    async updateProspect(arg0: Prospect): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProspect(to_candid_Prospect_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProspect(to_candid_Prospect_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateQuote(arg0: Quote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuote(to_candid_Quote_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuote(to_candid_Quote_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTransaction(arg0: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(to_candid_Transaction_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(to_candid_Transaction_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Client_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_JobEntry_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobEntry): JobEntry {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ProspectStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProspectStatus): ProspectStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Prospect_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prospect): Prospect {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_QuoteStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuoteStatus): QuoteStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Quote_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quote): Quote {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    fullName: string;
    isActive: boolean;
    gpsLocation: [] | [string];
    address: string;
    notes: string;
    phone: string;
    registrationDate: _Time;
}): {
    id: string;
    fullName: string;
    isActive: boolean;
    gpsLocation?: string;
    address: string;
    notes: string;
    phone: string;
    registrationDate: Time;
} {
    return {
        id: value.id,
        fullName: value.fullName,
        isActive: value.isActive,
        gpsLocation: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.gpsLocation)),
        address: value.address,
        notes: value.notes,
        phone: value.phone,
        registrationDate: value.registrationDate
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: string;
    status: _JobStatus;
    clientId: string;
    endTime: string;
    scheduledDate: string;
    assignedWorker: string;
    serviceDescription: string;
}): {
    id: string;
    startTime: string;
    status: JobStatus;
    clientId: string;
    endTime: string;
    scheduledDate: string;
    assignedWorker: string;
    serviceDescription: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_JobStatus_n28(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        endTime: value.endTime,
        scheduledDate: value.scheduledDate,
        assignedWorker: value.assignedWorker,
        serviceDescription: value.serviceDescription
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ProspectStatus;
    name: string;
    serviceRequested: string;
    address: string;
    phone: string;
    quoteDate: _Time;
}): {
    id: string;
    status: ProspectStatus;
    name: string;
    serviceRequested: string;
    address: string;
    phone: string;
    quoteDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_ProspectStatus_n33(_uploadFile, _downloadFile, value.status),
        name: value.name,
        serviceRequested: value.serviceRequested,
        address: value.address,
        phone: value.phone,
        quoteDate: value.quoteDate
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _QuoteStatus;
    clientId: string;
    serviceDescription: string;
    creationDate: _Time;
    expirationDate: _Time;
    price: number;
}): {
    id: string;
    status: QuoteStatus;
    clientId: string;
    serviceDescription: string;
    creationDate: Time;
    expirationDate: Time;
    price: number;
} {
    return {
        id: value.id,
        status: from_candid_QuoteStatus_n38(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        serviceDescription: value.serviceDescription,
        creationDate: value.creationDate,
        expirationDate: value.expirationDate,
        price: value.price
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transactionDate: _Time;
    transactionType: _TransactionType;
    description: string;
    amount: number;
}): {
    id: string;
    transactionDate: Time;
    transactionType: TransactionType;
    description: string;
    amount: number;
} {
    return {
        id: value.id,
        transactionDate: value.transactionDate,
        transactionType: from_candid_TransactionType_n43(_uploadFile, _downloadFile, value.transactionType),
        description: value.description,
        amount: value.amount
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): JobStatus {
    return "cancelled" in value ? JobStatus.cancelled : "pending" in value ? JobStatus.pending : "completed" in value ? JobStatus.completed : "inProgress" in value ? JobStatus.inProgress : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quoteSent: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): ProspectStatus {
    return "quoteSent" in value ? ProspectStatus.quoteSent : "pending" in value ? ProspectStatus.pending : "rejected" in value ? ProspectStatus.rejected : "accepted" in value ? ProspectStatus.accepted : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    sent: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): QuoteStatus {
    return "pending" in value ? QuoteStatus.pending : "sent" in value ? QuoteStatus.sent : "rejected" in value ? QuoteStatus.rejected : "accepted" in value ? QuoteStatus.accepted : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
}): TransactionType {
    return "expense" in value ? TransactionType.expense : "income" in value ? TransactionType.income : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobEntry>): Array<JobEntry> {
    return value.map((x)=>from_candid_JobEntry_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Prospect>): Array<Prospect> {
    return value.map((x)=>from_candid_Prospect_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quote>): Array<Quote> {
    return value.map((x)=>from_candid_Quote_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n41(_uploadFile, _downloadFile, x));
}
function to_candid_Client_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Client): _Client {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_JobEntry_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobEntry): _JobEntry {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_JobStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ProspectStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProspectStatus): _ProspectStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Prospect_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Prospect): _Prospect {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_QuoteStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuoteStatus): _QuoteStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Quote_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Quote): _Quote {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: QuoteStatus;
    clientId: string;
    serviceDescription: string;
    creationDate: Time;
    expirationDate: Time;
    price: number;
}): {
    id: string;
    status: _QuoteStatus;
    clientId: string;
    serviceDescription: string;
    creationDate: _Time;
    expirationDate: _Time;
    price: number;
} {
    return {
        id: value.id,
        status: to_candid_QuoteStatus_n13(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        serviceDescription: value.serviceDescription,
        creationDate: value.creationDate,
        expirationDate: value.expirationDate,
        price: value.price
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transactionDate: Time;
    transactionType: TransactionType;
    description: string;
    amount: number;
}): {
    id: string;
    transactionDate: _Time;
    transactionType: _TransactionType;
    description: string;
    amount: number;
} {
    return {
        id: value.id,
        transactionDate: value.transactionDate,
        transactionType: to_candid_TransactionType_n17(_uploadFile, _downloadFile, value.transactionType),
        description: value.description,
        amount: value.amount
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    fullName: string;
    isActive: boolean;
    gpsLocation?: string;
    address: string;
    notes: string;
    phone: string;
    registrationDate: Time;
}): {
    id: string;
    fullName: string;
    isActive: boolean;
    gpsLocation: [] | [string];
    address: string;
    notes: string;
    phone: string;
    registrationDate: _Time;
} {
    return {
        id: value.id,
        fullName: value.fullName,
        isActive: value.isActive,
        gpsLocation: value.gpsLocation ? candid_some(value.gpsLocation) : candid_none(),
        address: value.address,
        notes: value.notes,
        phone: value.phone,
        registrationDate: value.registrationDate
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: string;
    status: JobStatus;
    clientId: string;
    endTime: string;
    scheduledDate: string;
    assignedWorker: string;
    serviceDescription: string;
}): {
    id: string;
    startTime: string;
    status: _JobStatus;
    clientId: string;
    endTime: string;
    scheduledDate: string;
    assignedWorker: string;
    serviceDescription: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: to_candid_JobStatus_n5(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        endTime: value.endTime,
        scheduledDate: value.scheduledDate,
        assignedWorker: value.assignedWorker,
        serviceDescription: value.serviceDescription
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: ProspectStatus;
    name: string;
    serviceRequested: string;
    address: string;
    phone: string;
    quoteDate: Time;
}): {
    id: string;
    status: _ProspectStatus;
    name: string;
    serviceRequested: string;
    address: string;
    phone: string;
    quoteDate: _Time;
} {
    return {
        id: value.id,
        status: to_candid_ProspectStatus_n9(_uploadFile, _downloadFile, value.status),
        name: value.name,
        serviceRequested: value.serviceRequested,
        address: value.address,
        phone: value.phone,
        quoteDate: value.quoteDate
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProspectStatus): {
    quoteSent: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == ProspectStatus.quoteSent ? {
        quoteSent: null
    } : value == ProspectStatus.pending ? {
        pending: null
    } : value == ProspectStatus.rejected ? {
        rejected: null
    } : value == ProspectStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuoteStatus): {
    pending: null;
} | {
    sent: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == QuoteStatus.pending ? {
        pending: null
    } : value == QuoteStatus.sent ? {
        sent: null
    } : value == QuoteStatus.rejected ? {
        rejected: null
    } : value == QuoteStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    expense: null;
} | {
    income: null;
} {
    return value == TransactionType.expense ? {
        expense: null
    } : value == TransactionType.income ? {
        income: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == JobStatus.cancelled ? {
        cancelled: null
    } : value == JobStatus.pending ? {
        pending: null
    } : value == JobStatus.completed ? {
        completed: null
    } : value == JobStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
